In [1]:
import numpy as np

In [17]:
#one dimensuional array
a=np.array([3,5,7,4,2])
print(a)
print("Dimension:",a.ndim)
print("Byte size:",a.itemsize)
print("Type:",a.dtype)
print("Number of elements:",a.size)
print("Total size:",a.nbytes)
print("Shape:",a.shape)

[3 5 7 4 2]
Dimension: 1
Byte size: 4
Type: int32
Number of elements: 5
Total size: 20
Shape: (5,)


In [18]:
#two dimensionl array
b=np.array([(21,40,62),(33,57,74)],float)
print(b)
print("Dimension:",b.ndim)
print("Byte size:",b.itemsize)
print("Type:",b.dtype)
print("Number of elements:",b.size)
print("Total size:",b.nbytes)
print("Shape:",b.shape)

[[21. 40. 62.]
 [33. 57. 74.]]
Dimension: 2
Byte size: 8
Type: float64
Number of elements: 6
Total size: 48
Shape: (2, 3)


In [19]:
#Reshape
print(b.reshape(3,2))

[[21. 40.]
 [62. 33.]
 [57. 74.]]


In [21]:
#slicing
print(b[0,2])

print(b[0,:])

print(b[0:,2])

62.0
[21. 40. 62.]
[62. 74.]


In [30]:
# 5 sequence btw 1 and10
l=np.linspace(1,10,5)
print(l)


[ 1.    3.25  5.5   7.75 10.  ]


In [31]:
print("Max:",b.max())
print("Min:",b.min())
print("Sum:",b.sum())
print("Sum of axis 0:",b.sum(axis=0))
print("Sum of axis 1:",b.sum(axis=1))
print("Mean:",b.mean())
print("Standard deviation:",b.std())
print("Square root:",np.sqrt(b))


Max: 74.0
Min: 21.0
Sum: 287.0
Sum of axis 0: [ 54.  97. 136.]
Sum of axis 1: [123. 164.]
Mean: 47.833333333333336
Standard deviation: 18.123802642442953
Square root: [[4.58257569 6.32455532 7.87400787]
 [5.74456265 7.54983444 8.60232527]]


In [32]:
print(b.ravel())

[21. 40. 62. 33. 57. 74.]


In [34]:
p=np.array([(1,2,3),(3,4,5),(6,7,8)])
q=np.array([(11,65,12),(2,4,7),(4,23,10)])
print("P=")
print(p)
print("Q=")
print(q)

P=
[[1 2 3]
 [3 4 5]
 [6 7 8]]
Q=
[[11 65 12]
 [ 2  4  7]
 [ 4 23 10]]


In [35]:
print("P+Q")
print(p+q)

P+Q
[[12 67 15]
 [ 5  8 12]
 [10 30 18]]


In [36]:
print("P-Q")
print(p-q)

P-Q
[[-10 -63  -9]
 [  1   0  -2]
 [  2 -16  -2]]


In [37]:
print("P*Q")
print(p*q)

P*Q
[[ 11 130  36]
 [  6  16  35]
 [ 24 161  80]]


In [38]:
print("P/Q")
print(p/q)

P/Q
[[0.09090909 0.03076923 0.25      ]
 [1.5        1.         0.71428571]
 [1.5        0.30434783 0.8       ]]


In [39]:
print("P%Q")
print(p%q)

P%Q
[[1 2 3]
 [1 0 5]
 [2 7 8]]


In [40]:
print("P**Q")
print(p**q)

P**Q
[[         1          0     531441]
 [         9        256      78125]
 [      1296  821077879 1073741824]]


In [ ]:
print("Vertical:")
print(np.vstack((p,q)))
print(np.hstack((p,q)))