In [1]:
import numpy as np

In [2]:
#one dimensional array
a=np.array([3,5,7,4])
print(a)

[3 5 7 4]


In [3]:
#two dimensionl array
b=np.array([(2,4,6),(3,5,7)])
print(b)

[[2 4 6]
 [3 5 7]]


In [6]:
#memory size
import sys
s=range(1000)#list
print(sys.getsizeof(5)*len(s))

d=np.arange(1000)#numpy array
print(d.size*d.itemsize)

28000
4000


In [7]:
#dimension
p=np.array([1,2,3])
print(p.ndim)

1


In [8]:
q=np.array([(1,2,3),(4,5,6)])
print(q.ndim)

2


In [9]:
r=np.array([(1,2,3),(3,5,6),(3,7,8),(1,3,5)])
print(r.ndim)

2


In [11]:
#byte size
print(q.itemsize)

4


In [12]:
#datatype
print(r.dtype)

int32


In [13]:
#convert float
d=np.array([1,2,5],'float32')
print(d)

[1. 2. 5.]


In [14]:
print(d.dtype)

float32


In [15]:
#size(no of elements)
print(r.size)

12


In [16]:
#get total size
print(p.nbytes)

12


In [18]:
#shape of array
x=np.array([(1,2,3),(4,5,6)])
print(x.shape)

(2, 3)


In [20]:
#reshape
y=np.array([(1,2,3,4),(3,5,6,7)])
print(y.reshape(4,2))

[[1 2]
 [3 4]
 [3 5]
 [6 7]]


In [26]:
#slicing
z=np.array([(1,2,3,4),(9,8,7,6)])
print(z)

print(z[0,3])

print(z[0,:])

print(z[0:,2])

[[1 2 3 4]
 [9 8 7 6]]
4
[1 2 3 4]
[3 7]


In [27]:
w=np.array([(1,2,3),(3,5,6),(3,7,8),(1,3,5)])
print(w[0:3,1])

[2 5 7]


In [30]:
# 5 sequence btw 5 and10
l=np.linspace(5,10,5)
print(l)

m=np.linspace(1,10,9)
print(m)

[ 5.    6.25  7.5   8.75 10.  ]
[ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]


In [32]:
n=np.array([(1,3,5,7)])
print(n.max())
print(n.min())
print(n.sum())

7
1
16


In [35]:
s=np.array([(10,20,30),(45,55,65)])
print(s)
#sum of columns
print(s.sum(axis=0))
#sum of rows
print(s.sum(axis=1))

[[10 20 30]
 [45 55 65]]
[55 75 95]
[ 60 165]


In [37]:
#sqaure root
a=np.array([(1,2,3,4),(5,6,7,8)])
print(a)
print(np.sqrt(a))

[[1 2 3 4]
 [5 6 7 8]]
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]]


In [39]:
#standard deviation
print(np.std(a))

2.29128784747792


In [42]:
p=np.array([(1,2,3),(3,4,5),(6,7,8)])
q=np.array([(11,65,12),(2,4,7),(4,23,10)])
print(p+q)

[[12 67 15]
 [ 5  8 12]
 [10 30 18]]


In [43]:
print(q-p)

[[10 63  9]
 [-1  0  2]
 [-2 16  2]]


In [49]:
print(p*q)

[[ 11 130  36]
 [  6  16  35]
 [ 24 161  80]]


In [45]:
print(p/q)

[[0.09090909 0.03076923 0.25      ]
 [1.5        1.         0.71428571]
 [1.5        0.30434783 0.8       ]]


In [93]:
print(p%q)

[[1 2 3]
 [1 0 5]
 [2 7 8]]


In [94]:
print(p**q)

[[         1          0     531441]
 [         9        256      78125]
 [      1296  821077879 1073741824]]


In [47]:
#concatenate(vertical stacking)
print(np.vstack((p,q)))

[[ 1  2  3]
 [ 3  4  5]
 [ 6  7  8]
 [11 65 12]
 [ 2  4  7]
 [ 4 23 10]]


In [48]:
#horizontal stack
print(np.hstack((p,q)))

[[ 1  2  3 11 65 12]
 [ 3  4  5  2  4  7]
 [ 6  7  8  4 23 10]]


In [50]:
#to make single column
print(p.ravel())

[1 2 3 3 4 5 6 7 8]


In [51]:
#exponential
print(np.exp(p))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [2.00855369e+01 5.45981500e+01 1.48413159e+02]
 [4.03428793e+02 1.09663316e+03 2.98095799e+03]]


In [52]:
#natural log
print(np.log(p))

[[0.         0.69314718 1.09861229]
 [1.09861229 1.38629436 1.60943791]
 [1.79175947 1.94591015 2.07944154]]


In [53]:
#log10
print(np.log10(p))

[[0.         0.30103    0.47712125]
 [0.47712125 0.60205999 0.69897   ]
 [0.77815125 0.84509804 0.90308999]]


In [55]:
a=np.array([1,4,5,8])
print(a)

[1 4 5 8]


In [57]:
print(type(a))

<class 'numpy.ndarray'>


In [58]:
print(a[:2])

[1 4]


In [59]:
print(a[3])

8


In [60]:
a[0]=5
print(a)

[5 4 5 8]


In [61]:
a=np.array([[1,2,3],[4,5,8]])
print(a)

[[1 2 3]
 [4 5 8]]


In [63]:
print(a[0,0])

1


In [64]:
print(a[1,:])

[4 5 8]


In [65]:
print(a[:,2])

[3 8]


In [66]:
print(a[-1:,-2:])

[[5 8]]


In [68]:
print(a.shape)

(2, 3)


In [69]:
print(a.dtype)

int32


In [70]:
#length of first axis
print(len(a))

2


In [71]:
print(8 in a)

True


In [72]:
print(10 in a)

False


In [73]:
a=np.array(range(10))
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [74]:
print(a.reshape(5,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [75]:
#COPY FUNCTION
a=np.array([1,2,3])
b=a
c=a.copy()
a[0]=0
print(a)

[0 2 3]


In [76]:
print(b)

[0 2 3]


In [77]:
print(c)

[1 2 3]


In [78]:
a=np.array([1,2,3],float)
print(a)

[1. 2. 3.]


In [80]:
print(a.tolist())

[1.0, 2.0, 3.0]


In [81]:
print(list(a))

[1.0, 2.0, 3.0]


In [114]:
a=np.array([1,2,3],'float')
s=a.tostring()
print(s)
np.fromstring(s)

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'


<ipython-input-114-81f659fadfd9>:2: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  s=a.tostring()
<ipython-input-114-81f659fadfd9>:4: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring(s)


array([1., 2., 3.])

In [112]:
a=np.array([1,2,3])
print(a)
a.fill(0)
print(a)

[1 2 3]
[0 0 0]


In [91]:
a=np.array([(1,2,3,4),(5,6,7,8)])
print(a)
print(a.transpose())

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [92]:
print(a.flatten())

[1 2 3 4 5 6 7 8]


In [95]:
a=np.array([1,4,5])
for i in a:
    print(i)

1
4
5


In [96]:
a=np.array([[1,2],[3,4],[5,6]])
for i in a:
    print(i)

[1 2]
[3 4]
[5 6]


In [97]:
for (i,j) in a:
    print(i*j)

2
12
30


In [98]:
print(a.sum())

21


In [99]:
#product
print(a.prod())

720


In [100]:
print(a.mean())

3.5


In [101]:
print(a.var())

2.9166666666666665


In [102]:
print(a.std())

1.707825127659933


In [104]:
print(a.max())

6


In [105]:
#return tghe index of min value
print(a.argmin())

0


In [108]:
a=np.array([[0,2],[3,-1],[3,5]])
print(a.mean(axis=0))
print(a.mean(axis=1))
print(a.min(axis=1))
print(a.max(axis=0))

[2. 2.]
[1. 1. 4.]
[ 0 -1  3]
[3 5]
