In [1]:
import pandas as pd
import numpy as np

In [2]:
#create series
#np.nan:null value
s=pd.Series([1,2,3,4,5,6,np.nan,8,9,10])
print(s)

0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     NaN
7     8.0
8     9.0
9    10.0
dtype: float64


In [3]:
#dataframe
d=pd.date_range('20211006',periods=10)
print(d)

DatetimeIndex(['2021-10-06', '2021-10-07', '2021-10-08', '2021-10-09',
               '2021-10-10', '2021-10-11', '2021-10-12', '2021-10-13',
               '2021-10-14', '2021-10-15'],
              dtype='datetime64[ns]', freq='D')


In [4]:
#random.randn:random values
df=pd.DataFrame(np.random.randn(10,4),index=d,columns=['A','B','C','D'])
print(df)

                   A         B         C         D
2021-10-06  1.265219 -0.410078  1.796779  2.139005
2021-10-07  0.249236 -1.481760  1.474949  0.218890
2021-10-08 -1.006484 -0.614809  0.166473 -0.036889
2021-10-09 -1.430111  1.166568 -1.708489  0.258380
2021-10-10 -0.267445  1.735814  0.251221 -1.050228
2021-10-11 -0.570989 -1.252369  0.381064 -0.185881
2021-10-12  0.209009  0.828044 -0.549401 -1.128903
2021-10-13  2.081997  0.285098  0.950503  0.097531
2021-10-14 -0.814042  0.167715 -1.248003 -0.319357
2021-10-15  1.446248 -1.288673 -0.818310  0.056380


In [5]:
#dataframe by passing a dictionary
df1=pd.DataFrame({'A':[1,2,3,4],
                  'B':pd.Timestamp('20211006'),
                 'C':pd.Series(1,index=list(range(4)),dtype='float32'),
                 'D':np.array([5]*4,dtype='int32'),
                 'E':pd.Categorical(['true','false','True','False']),
                 'F':'Pandas'})
print(df1)

   A          B    C  D      E       F
0  1 2021-10-06  1.0  5   true  Pandas
1  2 2021-10-06  1.0  5  false  Pandas
2  3 2021-10-06  1.0  5   True  Pandas
3  4 2021-10-06  1.0  5  False  Pandas


In [6]:
#check datatype
print(df1.dtypes)

A             int64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object


In [7]:
print(df.dtypes)

A    float64
B    float64
C    float64
D    float64
dtype: object


In [8]:
#first five values
print(df.head())

                   A         B         C         D
2021-10-06  1.265219 -0.410078  1.796779  2.139005
2021-10-07  0.249236 -1.481760  1.474949  0.218890
2021-10-08 -1.006484 -0.614809  0.166473 -0.036889
2021-10-09 -1.430111  1.166568 -1.708489  0.258380
2021-10-10 -0.267445  1.735814  0.251221 -1.050228


In [9]:
#last five values
print(df.tail())

                   A         B         C         D
2021-10-11 -0.570989 -1.252369  0.381064 -0.185881
2021-10-12  0.209009  0.828044 -0.549401 -1.128903
2021-10-13  2.081997  0.285098  0.950503  0.097531
2021-10-14 -0.814042  0.167715 -1.248003 -0.319357
2021-10-15  1.446248 -1.288673 -0.818310  0.056380


In [10]:
#index values
print(df.index)

DatetimeIndex(['2021-10-06', '2021-10-07', '2021-10-08', '2021-10-09',
               '2021-10-10', '2021-10-11', '2021-10-12', '2021-10-13',
               '2021-10-14', '2021-10-15'],
              dtype='datetime64[ns]', freq='D')


In [11]:
#columns
print(df.columns)

Index(['A', 'B', 'C', 'D'], dtype='object')


In [12]:
#numpy representation
print(df.to_numpy())

[[ 1.26521918 -0.4100785   1.79677871  2.13900503]
 [ 0.24923589 -1.48175957  1.47494866  0.21888982]
 [-1.00648353 -0.61480939  0.16647326 -0.03688877]
 [-1.43011063  1.16656774 -1.70848861  0.25838027]
 [-0.26744485  1.73581429  0.25122065 -1.05022768]
 [-0.57098888 -1.25236939  0.38106395 -0.18588061]
 [ 0.20900857  0.82804355 -0.54940109 -1.12890266]
 [ 2.08199743  0.28509813  0.95050252  0.09753134]
 [-0.81404171  0.16771487 -1.24800306 -0.31935731]
 [ 1.44624821 -1.28867311 -0.81830955  0.05637986]]


In [13]:
#describe the data
print(df.describe())

               A          B          C          D
count  10.000000  10.000000  10.000000  10.000000
mean    0.116264  -0.086445   0.069679   0.004893
std     1.160278   1.108810   1.151942   0.895530
min    -1.430111  -1.481760  -1.708489  -1.128903
25%    -0.753279  -1.092979  -0.751082  -0.285988
50%    -0.029218  -0.121182   0.208847   0.009746
75%     1.011223   0.692307   0.808143   0.188550
max     2.081997   1.735814   1.796779   2.139005


In [14]:
#sorted by index
print(df.sort_index(axis=1,ascending=False))

                   D         C         B         A
2021-10-06  2.139005  1.796779 -0.410078  1.265219
2021-10-07  0.218890  1.474949 -1.481760  0.249236
2021-10-08 -0.036889  0.166473 -0.614809 -1.006484
2021-10-09  0.258380 -1.708489  1.166568 -1.430111
2021-10-10 -1.050228  0.251221  1.735814 -0.267445
2021-10-11 -0.185881  0.381064 -1.252369 -0.570989
2021-10-12 -1.128903 -0.549401  0.828044  0.209009
2021-10-13  0.097531  0.950503  0.285098  2.081997
2021-10-14 -0.319357 -1.248003  0.167715 -0.814042
2021-10-15  0.056380 -0.818310 -1.288673  1.446248


In [15]:
#sorted by values
print(df.sort_values(by='C'))

                   A         B         C         D
2021-10-09 -1.430111  1.166568 -1.708489  0.258380
2021-10-14 -0.814042  0.167715 -1.248003 -0.319357
2021-10-15  1.446248 -1.288673 -0.818310  0.056380
2021-10-12  0.209009  0.828044 -0.549401 -1.128903
2021-10-08 -1.006484 -0.614809  0.166473 -0.036889
2021-10-10 -0.267445  1.735814  0.251221 -1.050228
2021-10-11 -0.570989 -1.252369  0.381064 -0.185881
2021-10-13  2.081997  0.285098  0.950503  0.097531
2021-10-07  0.249236 -1.481760  1.474949  0.218890
2021-10-06  1.265219 -0.410078  1.796779  2.139005


In [16]:
#access single column
print(df['B'])

2021-10-06   -0.410078
2021-10-07   -1.481760
2021-10-08   -0.614809
2021-10-09    1.166568
2021-10-10    1.735814
2021-10-11   -1.252369
2021-10-12    0.828044
2021-10-13    0.285098
2021-10-14    0.167715
2021-10-15   -1.288673
Freq: D, Name: B, dtype: float64


In [17]:
#slicing
print(df[0:4])

                   A         B         C         D
2021-10-06  1.265219 -0.410078  1.796779  2.139005
2021-10-07  0.249236 -1.481760  1.474949  0.218890
2021-10-08 -1.006484 -0.614809  0.166473 -0.036889
2021-10-09 -1.430111  1.166568 -1.708489  0.258380


In [18]:
#loc method
print(df.loc[:,['A','C']])

                   A         C
2021-10-06  1.265219  1.796779
2021-10-07  0.249236  1.474949
2021-10-08 -1.006484  0.166473
2021-10-09 -1.430111 -1.708489
2021-10-10 -0.267445  0.251221
2021-10-11 -0.570989  0.381064
2021-10-12  0.209009 -0.549401
2021-10-13  2.081997  0.950503
2021-10-14 -0.814042 -1.248003
2021-10-15  1.446248 -0.818310


In [19]:
print(df.loc['20211010':'20211015',['D','C']])

                   D         C
2021-10-10 -1.050228  0.251221
2021-10-11 -0.185881  0.381064
2021-10-12 -1.128903 -0.549401
2021-10-13  0.097531  0.950503
2021-10-14 -0.319357 -1.248003
2021-10-15  0.056380 -0.818310


In [20]:
print(df.loc[d[0],['D','C']])

D    2.139005
C    1.796779
Name: 2021-10-06 00:00:00, dtype: float64


In [21]:
#get exact value
print(df.at[d[0],'C'])

1.7967787106894435


In [22]:
#all the value from 3rd position
print(df.iloc[3])

A   -1.430111
B    1.166568
C   -1.708489
D    0.258380
Name: 2021-10-09 00:00:00, dtype: float64


In [23]:
print(df.iloc[3:5])

                   A         B         C         D
2021-10-09 -1.430111  1.166568 -1.708489  0.258380
2021-10-10 -0.267445  1.735814  0.251221 -1.050228


In [24]:
print(df.iloc[3:5,0:2])

                   A         B
2021-10-09 -1.430111  1.166568
2021-10-10 -0.267445  1.735814


In [25]:
print(df[df['A']>0])

                   A         B         C         D
2021-10-06  1.265219 -0.410078  1.796779  2.139005
2021-10-07  0.249236 -1.481760  1.474949  0.218890
2021-10-12  0.209009  0.828044 -0.549401 -1.128903
2021-10-13  2.081997  0.285098  0.950503  0.097531
2021-10-15  1.446248 -1.288673 -0.818310  0.056380


In [26]:
print(df[df['A']>1])

                   A         B         C         D
2021-10-06  1.265219 -0.410078  1.796779  2.139005
2021-10-13  2.081997  0.285098  0.950503  0.097531
2021-10-15  1.446248 -1.288673 -0.818310  0.056380


In [27]:
df2=df.reindex(index=d[0:4],columns=list(df.columns)+['E'])
df2.loc[d[0]:d[1],'E']=1
print(df2)

                   A         B         C         D    E
2021-10-06  1.265219 -0.410078  1.796779  2.139005  1.0
2021-10-07  0.249236 -1.481760  1.474949  0.218890  1.0
2021-10-08 -1.006484 -0.614809  0.166473 -0.036889  NaN
2021-10-09 -1.430111  1.166568 -1.708489  0.258380  NaN


In [28]:
print(df2.isnull())

                A      B      C      D      E
2021-10-06  False  False  False  False  False
2021-10-07  False  False  False  False  False
2021-10-08  False  False  False  False   True
2021-10-09  False  False  False  False   True


In [29]:
#drop null columns
print(df2.dropna())

                   A         B         C         D    E
2021-10-06  1.265219 -0.410078  1.796779  2.139005  1.0
2021-10-07  0.249236 -1.481760  1.474949  0.218890  1.0


In [30]:
#fill null values
print(df2.fillna(value=2))

                   A         B         C         D    E
2021-10-06  1.265219 -0.410078  1.796779  2.139005  1.0
2021-10-07  0.249236 -1.481760  1.474949  0.218890  1.0
2021-10-08 -1.006484 -0.614809  0.166473 -0.036889  2.0
2021-10-09 -1.430111  1.166568 -1.708489  0.258380  2.0


In [31]:
print(df.mean())

A    0.116264
B   -0.086445
C    0.069679
D    0.004893
dtype: float64


In [32]:
s=pd.Series([1,2,3,np.nan,4,5,6,7,8,9],index=d).shift(2)
print(s)

2021-10-06    NaN
2021-10-07    NaN
2021-10-08    1.0
2021-10-09    2.0
2021-10-10    3.0
2021-10-11    NaN
2021-10-12    4.0
2021-10-13    5.0
2021-10-14    6.0
2021-10-15    7.0
Freq: D, dtype: float64


In [33]:
#substract d by s
print(df.sub(s,axis='index'))

                   A         B         C         D
2021-10-06       NaN       NaN       NaN       NaN
2021-10-07       NaN       NaN       NaN       NaN
2021-10-08 -2.006484 -1.614809 -0.833527 -1.036889
2021-10-09 -3.430111 -0.833432 -3.708489 -1.741620
2021-10-10 -3.267445 -1.264186 -2.748779 -4.050228
2021-10-11       NaN       NaN       NaN       NaN
2021-10-12 -3.790991 -3.171956 -4.549401 -5.128903
2021-10-13 -2.918003 -4.714902 -4.049497 -4.902469
2021-10-14 -6.814042 -5.832285 -7.248003 -6.319357
2021-10-15 -5.553752 -8.288673 -7.818310 -6.943620


In [34]:
print(df)

                   A         B         C         D
2021-10-06  1.265219 -0.410078  1.796779  2.139005
2021-10-07  0.249236 -1.481760  1.474949  0.218890
2021-10-08 -1.006484 -0.614809  0.166473 -0.036889
2021-10-09 -1.430111  1.166568 -1.708489  0.258380
2021-10-10 -0.267445  1.735814  0.251221 -1.050228
2021-10-11 -0.570989 -1.252369  0.381064 -0.185881
2021-10-12  0.209009  0.828044 -0.549401 -1.128903
2021-10-13  2.081997  0.285098  0.950503  0.097531
2021-10-14 -0.814042  0.167715 -1.248003 -0.319357
2021-10-15  1.446248 -1.288673 -0.818310  0.056380


In [35]:
#cumulative sum
print(df.apply(np.cumsum))

                   A         B         C         D
2021-10-06  1.265219 -0.410078  1.796779  2.139005
2021-10-07  1.514455 -1.891838  3.271727  2.357895
2021-10-08  0.507972 -2.506647  3.438201  2.321006
2021-10-09 -0.922139 -1.340080  1.729712  2.579386
2021-10-10 -1.189584  0.395735  1.980933  1.529159
2021-10-11 -1.760573 -0.856635  2.361997  1.343278
2021-10-12 -1.551564 -0.028591  1.812596  0.214375
2021-10-13  0.530433  0.256507  2.763098  0.311907
2021-10-14 -0.283609  0.424222  1.515095 -0.007451
2021-10-15  1.162640 -0.864451  0.696785  0.048929


In [36]:
print(df.apply(lambda x:x.max()-x.min()))

A    3.512108
B    3.217574
C    3.505267
D    3.267908
dtype: float64


In [37]:
print(s.value_counts())

3.0    1
7.0    1
6.0    1
4.0    1
2.0    1
5.0    1
1.0    1
dtype: int64


In [38]:
s=pd.Series(['pandas','python','jupyter',np.nan,'java','colab'])
print(s.str.upper())

0     PANDAS
1     PYTHON
2    JUPYTER
3        NaN
4       JAVA
5      COLAB
dtype: object


In [39]:
df=pd.DataFrame(np.random.randn(10,4))
print(df)

          0         1         2         3
0 -0.004866 -0.490435 -0.343996  2.094336
1  0.232624 -2.058152  1.517612  1.342595
2  0.753776  0.056186  0.008713 -0.816360
3  0.377515 -1.179499 -0.301431 -0.414765
4 -1.060267  0.157136 -1.161921  1.174944
5 -0.531232  2.924786  0.111726 -0.292541
6  0.062195 -0.884605 -0.638533 -0.762899
7 -0.293283 -1.604799 -0.016716 -0.790920
8  0.042356 -0.241014 -1.342244  0.580102
9  0.042341 -3.278765 -0.478191 -1.766736


In [40]:
#break the dataframe
df2=[df[:3],df[3:7],df[7:]]
df2

[          0         1         2         3
 0 -0.004866 -0.490435 -0.343996  2.094336
 1  0.232624 -2.058152  1.517612  1.342595
 2  0.753776  0.056186  0.008713 -0.816360,
           0         1         2         3
 3  0.377515 -1.179499 -0.301431 -0.414765
 4 -1.060267  0.157136 -1.161921  1.174944
 5 -0.531232  2.924786  0.111726 -0.292541
 6  0.062195 -0.884605 -0.638533 -0.762899,
           0         1         2         3
 7 -0.293283 -1.604799 -0.016716 -0.790920
 8  0.042356 -0.241014 -1.342244  0.580102
 9  0.042341 -3.278765 -0.478191 -1.766736]

In [41]:
#concat the several pieces
pd.concat(df2)

0         1         2         3
0 -0.004866 -0.490435 -0.343996  2.094336
1  0.232624 -2.058152  1.517612  1.342595
2  0.753776  0.056186  0.008713 -0.816360
3  0.377515 -1.179499 -0.301431 -0.414765
4 -1.060267  0.157136 -1.161921  1.174944
5 -0.531232  2.924786  0.111726 -0.292541
6  0.062195 -0.884605 -0.638533 -0.762899
7 -0.293283 -1.604799 -0.016716 -0.790920
8  0.042356 -0.241014 -1.342244  0.580102
9  0.042341 -3.278765 -0.478191 -1.766736

In [42]:
left=pd.DataFrame({'A':[1,2],'B':[3,4]})
left

A  B
0  1  3
1  2  4

In [43]:
right=pd.DataFrame({'A':[3,2],'D':[4,5]})
right

A  D
0  3  4
1  2  5

In [44]:
pd.merge(left,right,on='A')

A  B  D
0  2  4  5

In [45]:
my_tuple=list(zip(*[[1,2,3,4,5,17,18,19],[11,12,13,6,7,8,9,10]]))
index=pd.MultiIndex.from_tuples(my_tuple,names=['First','Second'])
df=pd.DataFrame(np.random.randn(8,2),index=index,columns=['A','B'])
df

A         B
First Second                    
1     11      0.659006 -0.312015
2     12     -0.437089 -0.143997
3     13      0.354591 -0.537537
4     6       0.972277  0.226803
5     7       0.005226 -0.522762
17    8      -0.009387  1.027772
18    9      -0.316685  1.518098
19    10      0.638308  0.409384

In [46]:
df2=df[:2]
df2

A         B
First Second                    
1     11      0.659006 -0.312015
2     12     -0.437089 -0.143997

In [47]:
df2.stack()

First  Second   
1      11      A    0.659006
               B   -0.312015
2      12      A   -0.437089
               B   -0.143997
dtype: float64

In [48]:
df2.unstack()

A                   B          
Second        11        12        11        12
First                                         
1       0.659006       NaN -0.312015       NaN
2            NaN -0.437089       NaN -0.143997